# -*- coding: utf-8 -*-
"""Beautiful Soup Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oNdDI6JJELhdvPb02CzTtoHBLdg1QGcy

# Beautiful Soup Demo

This Beautiful Demo was created by Jean-Sébastien Marier. It is based on Codecademy's [Learn Web Scraping with Beautiful Soup](https://www.codecademy.com/enrolled/courses/learn-web-scraping) course. This script will extract a [list of the undergraduate programs](https://catalogue.uottawa.ca/en/programs/) offered by the University of Ottawa. Please note that this is by no means a comprehensive data extraction. It is merely an example to show a basic Beautiful Soup workflow.

# Démonstration Beautiful Soup

Cette démonstration de Beautiful Soup a été créée par Jean-Sébastien Marier. Elle est basée sur le cours [Learn Web Scraping with Beautiful Soup](https://www.codecademy.com/enrolled/courses/learn-web-scraping) de Codecademy. Ce script extraira une [liste des programmes de premier cycle](https://catalogue.uottawa.ca/en/programs/) offerts par l'Université d'Ottawa. Veuillez noter que cette extraction de données n'est pas exhaustive. Il s'agit simplement d'un exemple d'un flux de travail simple avec Beautiful Soup.
"""

#Let's import the required libraries and define our web page.
#Commençons par importer les bibliothèques requises et définir notre page web.

import requests
from bs4 import BeautifulSoup

webpage = requests.get("https://catalogue.uottawa.ca/en/programs/")
print(webpage.text)

#Let's parse our page's content.
#Analysons le contenu de notre page.

webpage_content = webpage.content

soup = BeautifulSoup(webpage_content, "html.parser")
print(soup)

#Now, we will extract the HTML elements with the names of the programs. We are looking for <span> tags with the class "title."
#Maintenant, nous allons extraire les éléments HTML qui contiennent les noms des programmes. Nous recherchons des balises <span> avec la classe « titre ».

programs = soup.find_all(attrs={"class":"title"})
print(programs)

#Lastly, let's do a loop that will extract the names of the programs from the HTML tags.
#Enfin, faisons une boucle qui extraira les noms des programmes des balises HTML.

for programnames in programs:
    print(programnames.text, programnames.next_sibling)